{{ if gt (len .Values.certs) 0 }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}-tls
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  tls:
    - secretName: "tls-{{ .Values.name }}"
      hosts:
        {{ range $item := .Values.certs }}
        - "mail.{{ $item.domain }}"
        - "imap.{{ $item.domain }}"
        - "smtp.{{ $item.domain }}"
        {{ end }}
  rules:
    {{ range $item := .Values.certs }}
    - host: "mail.{{ $item.domain }}"
    - host: "imap.{{ $item.domain }}"
    - host: "smtp.{{ $item.domain }}"
    {{ end }}
{{ end }}