name: build and deploy container

on:
  pull_request:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  service:
    uses: kubernetes-mail-server/.github/.github/workflows/service.yml@main
    secrets: inherit
    with:
      name: dovecot
      kind: statefulset
      helm-args: >-
        -f values.yaml
        --set server.storage=$(kubectl get cm -n mail-server general -o=jsonpath="{.data.STORAGE_SIZE}")
        --set ports.lmtp=$(kubectl get cm -n mail-server services-info -o=jsonpath="{.data.DOVECOT_LMTP}")
        --set ports.pop3=$(kubectl get cm -n mail-server services-info -o=jsonpath="{.data.DOVECOT_POP3}")
        --set ports.pop3-ssl=$(kubectl get cm -n mail-server services-info -o=jsonpath="{.data.DOVECOT_POP3_SSL}")
        --set ports.imap=$(kubectl get cm -n mail-server services-info -o=jsonpath="{.data.DOVECOT_IMAP}")
        --set ports.imap-ssl=$(kubectl get cm -n mail-server services-info -o=jsonpath="{.data.DOVECOT_IMAP_SSL}")
        --set ports.submission=$(kubectl get cm -n mail-server services-info -o=jsonpath="{.data.DOVECOT_SUBMISSION}")
